version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: bd-01
      MYSQL_USER: gerson
      MYSQL_PASSWORD: hprf35
      MYSQL_ROOT_PASSWORD: hprf35
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    image: php:apache
    restart: always
    volumes:
      - ./kraus/app:/var/www/html
    ports:
      - 8080:80
    links:
      - db:mysql
