 version: '3.7'
services:
  web:
    image: nginx:mainline
    ports:
      - "8000:80"
    volumes:
      - ../kraus:/usr/share/nginx/html
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: contract
      MYSQL_USER: kraus
      MYSQL_PASSWORD: hprf35
      MYSQL_ROOT_PASSWORD: hprf35
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql