version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: bd-01
      MYSQL_USER: gerson
      MYSQL_PASSWORD: hprf35
      MYSQL_ROOT_PASSWORD: hprf35
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    image: php:apache
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:80
    links:
      - db:mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hprf35
