version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    image: php:apache
    restart: always
    volumes:
      - ./kraus/app:/var/www/html
    ports:
      - 8080:80
    links:
      - db:mysql
